version: '3.8'

services:
  # 1. Webアプリコンテナ（Next.js）
  web:
    build: .
    container_name: todo-next-container
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development
      # 💡【超重要】Docker内のLocalStackコンテナへ向ける設定！
      - AWS_REGION=ap-northeast-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_ENDPOINT_URL=http://localstack:4566
      - NEXT_PUBLIC_S3_BUCKET_NAME=my-local-bucket
    # 💡 localstackコンテナが立ち上がってからwebを起動する
    depends_on:
      - localstack

  # 2. LocalStackコンテナ（S3モック環境）
  localstack:
    container_name: localstack_main
    image: localstack/localstack:3.4
    ports:
      - "127.0.0.1:4566:4566"
    environment:
      - SERVICES=s3
      - DEFAULT_REGION=ap-northeast-1
      - AWS_DEFAULT_REGION=ap-northeast-1
    volumes:
      - ./init-aws.sh:/etc/localstack/init/ready.d/init-aws.sh